// AppTraces-transformation
source
| where
    // RT0003 Authorization Succeeded (Pre Open Company)
    (tostring(Properties.eventId) <> 'RT0003') and
    // RT0004 Authorization Succeeded (Open Company)
    (tostring(Properties.eventId) <> 'RT0004') and
    // RT0006 Report rendering failed: {report ID} - {report name}
    (tostring(Properties.eventId) <> 'RT0006' or tostring(Message) startswith 'Report rendering failed:') and
    // RT0008 Incoming Web service requests
    (tostring(Properties.eventId) <> 'RT0008') and
    // RT0030 Error dialog displayed: {errorMessage}
    (tostring(Properties.eventId) <> 'RT0030' or tostring(Message) !startswith 'Error dialog shown:' or Properties !has 'alErrorMessage') and
    // LC0042 Task {taskId} removed: {codeunitObjectId}.
    (tostring(Properties.eventId) <> 'LC0042' or tostring(Properties.codeunitObjectId) <> '448') and
    // AL0000E24 Job queue entry enqueued: {alJobQueueId}
    // AL0000E25 Job queue entry started: {alJobQueueId}
    // AL0000E26 Job queue entry finished: {alJobQueueId}
    // AL0000CTA Feature Emailing is Discovered
    // AL0000CTQ Feature Emailing is Discovered
    // AL0000JLL Feature Bank reconciliation is Discovered
    // AL0000KMT Feature Dataverse Base Entities is Used
    // AL0000IOJ Feature Data Search is Discovered
    // AL0000H7N Entity sync
    // AL0000H7O Base entity synch
    // AL0000H7M Feature Dataverse is Used
    // AL0000HUU Feature Shopify is Discovered
    // AL0000IIL Base entity synch
    // AL0000LCP Feature Dataverse Multi-Company Synch is Used
    // AL0000LCR Entity sync
    // AL0000OUA Feature Master Data Management is Used
    // AL0000LH4 Feature Error Messages with Recommended Actions is Discovered
    // AL0000CTV Email sent successfully
    // AL0000FMG Running job queue once
    // AL0000CST Purchase document posted: *
    // AL0000CSU Sales document posted: *
    // AL0000GDP Feature Workflows is Used
    // AL0000KZV Job queue entry task cancelled:
    // AL0000LA2 Field added to changelog configuration
    // AL0000MEM Automatic cost adjustment was used.
    // LC0040 Task {taskId} created: {codeunitObjectId} scheduled to run after {notBefore}. Ready to run: {isReady}
    // LC0041 Task {taskId} ready: {codeunitObjectId} set ready to run after {notBefore}.
    // LC0057 Task {taskId} timeout changed to: {timeout} because it was exceeding the max timeout value.
    tostring(Properties.eventId) !in ('AL0000E24', 'AL0000E25', 'AL0000E26', 'AL0000CTA', 'AL0000CTQ', 'AL0000JLL', 'AL0000IOJ', 'AL0000HUU', 'AL0000LH4', 'AL0000CTV') and
    tostring(Properties.eventId) !in ('AL0000FMG', 'AL0000CST', 'AL0000CSU', 'AL0000GDP', 'AL0000KZV', 'AL0000LA2', 'AL0000MEM', 'LC0040', 'LC0041', 'LC0057') and
    tostring(Properties.eventId) !in ('AL0000H7N', 'AL0000KMT', 'AL0000H7O', 'AL0000H7M', 'AL0000IIL', 'AL0000LCP', 'AL0000LCR','AL0000OUA') and
    tostring(Properties.environmentType) == 'Production'
