// AppTraces-transformation
source
| where
    // RT0003 Authorization Succeeded (Pre Open Company)
    (tostring(Properties.eventId) <> 'RT0003') and
    // RT0004 Authorization Succeeded (Open Company)
    (tostring(Properties.eventId) <> 'RT0004') and
    // RT0006 Report rendering failed: {report ID} - {report name}
    (tostring(Properties.eventId) <> 'RT0006' or tostring(Properties.alObjectId) <> '1320') and
    // RT0030 Error dialog displayed: {errorMessage}
    (tostring(Properties.eventId) <> 'RT0030' or tostring(Message) !startswith 'Error dialog shown:' or Properties !has 'alErrorMessage') and
    // LC0042 Task {taskId} removed: {codeunitObjectId}.
    (tostring(Properties.eventId) <> 'LC0042' or tostring(Properties.codeunitObjectId) <> '448') and
    // AL0000E24 Job queue entry enqueued: {alJobQueueId}
    // AL0000E25 Job queue entry started: {alJobQueueId}
    // AL0000E26 Job queue entry finished: {alJobQueueId}
    // AL0000CTV Email sent successfully
    // AL0000FMG Running job queue once
    // AL0000CST Purchase document posted: *
    // AL0000CSU Sales document posted: *
    // AL0000GDP Feature Workflows is Used
    // AL0000KZV Job queue entry task cancelled:
    // AL0000LA2 Field added to changelog configuration
    // LC0040 Task {taskId} created: {codeunitObjectId} scheduled to run after {notBefore}. Ready to run: {isReady}
    // LC0041 Task {taskId} ready: {codeunitObjectId} set ready to run after {notBefore}.
    // LC0057 Task {taskId} timeout changed to: {timeout} because it was exceeding the max timeout value.
    tostring(Properties.eventId) !in ('AL0000E24', 'AL0000E25', 'AL0000E26', 'AL0000CTV', 'AL0000FMG', 'AL0000CST', 'AL0000CSU', 'AL0000GDP', 'AL0000KZV', 'AL0000LA2', 'LC0040', 'LC0041', 'LC0057') and
    tostring(Properties.environmentType) == 'Production'
