traces
| where timestamp >= ago(24h)
//| where tostring(customDimensions.eventId) == 'RT0008'
| where isnotempty(customDimensions.aadTenantId)
| extend
    companyName = tostring(customDimensions.companyName)
    ,EventId = tostring(customDimensions.eventId)
    ,Day = format_datetime(timestamp, "yyyy-MM-dd")
| project
    timestamp,
    companyName,
    customDimensions,
    Day,
    EventId
| summarize count = count() by EventId, Day, companyName
| order by companyName, Day desc, EventId asc
| render barchart