// Last Long running AL methods
// reference https://github.com/waldo1001/waldo.BCTelemetry/blob/master/Performance/SlowRunningAL/LastLongRunningAL.kql
// RT0005 - Performance - Operation exceeded time threshold (SQL query)
// RT0012 - Performance - Database lock timed out
// RT0018 - Performance - Operation exceeded time threshold (AL method)
traces
| where timestamp > ago(24h)
| where customDimensions has 'RT0018'
| where customDimensions.eventId == 'RT0018'
// | where customDimensions.eventId in ('RT0018','RT0005','RT0012')
| where customDimensions.alObjectId > 0
| project
    timestamp = timestamp
    ,environmentName = customDimensions.environmentName
    ,environmentType = customDimensions.environmentType
    ,companyName = customDimensions.companyName
    ,eventId = customDimensions.eventId
    ,alMethod = customDimensions.alMethod
    ,alObjectId = customDimensions.alObjectId
    ,alObjectName = customDimensions.alObjectName
    ,alObjectType = customDimensions.alObjectType
    ,alStackTrace = customDimensions.alStackTrace
    ,clientType = customDimensions.clientType
    ,exclusiveTime = customDimensions.exclusiveTime // This dimension was introduced in Business Central 2023 release wave 1, version 22.1. Backported to version 21.6
    ,totalTime = customDimensions.executionTime
    ,extensionId = customDimensions.extensionId
    ,extensionInfo = customDimensions.extensionInfo
    ,extensionName = customDimensions.extensionName
    ,extensionPublisher = customDimensions.extensionPublisher
    ,extensionVersion = customDimensions.extensionVersion
    ,longRunningThreshold = customDimensions.longRunningThreshold
    ,sqlExecutes = customDimensions.sqlExecutes // This dimension was introduced in Business Central 2023 release wave 1, version 22.0
    ,sqlRowsRead = customDimensions.sqlRowsRead // This dimension was introduced in Business Central 2023 release wave 1, version 22.0
| order by timestamp desc
| take 100